name: Build package
description: 'Build an npm package'
inputs:
  working-directory:  # sub-folder containing package
    description: 'Package Sub-Folder'
    required: true
  generate-types: # run generate-types indicator
    description: 'Run generate-types'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
        lock-file-name: ${{ inputs.working-directory }}/package-lock.json
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: npm-build-${{ env.cache-name }}-${{ inputs.working-directory }}-${{ hashFiles(env.lock-file-name) }}
        restore-keys: |
          npm-build-${{ env.cache-name }}-${{ inputs.working-directory }}-
          npm-build-${{ env.cache-name }}-

    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm ci

    - name: Generate Types
      shell: bash
      run: |
        if [ -n "${{ inputs.generate-types }}" ]
        then
          cd ${{ inputs.working-directory }}
          npm run generate-types
        fi

    - name: Build
      shell: bash
      run: |
        cd ${{ inputs.working-directory }}
        npm run rebuild
