name: 'Check for all vulnerabilities'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'
jobs:
  check-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.16.1'

      - name: Check EChartsBarChart (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/EChartsBarChart'

      - name: Check EChartsRadialTree (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/EChartsRadialTree'

      - name: Check ForceDirectedLayout (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/ForceDirectedLayout'

      - name: Check Lollipop (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/Lollipop'

      - name: Check ProcessFlow (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/ProcessFlow'

      - name: Check StretchedChord (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/StretchedChord'

      - name: Check WebpackD3MetaModel (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WebpackD3MetaModel'

      - name: Check WebpackD3Visualization (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WebpackD3Visualization'

      - name: Check WebpackReactVisualization (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WebpackReactVisualization'

      - name: Check WordCloud (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Examples/WordCloud'

      - name: Check EChartsCustomVisualizationTemplate (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Templates/EChartsCustomVisualizationTemplate'

      - name: Check EmptyCustomVisualizationTemplate (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Templates/EmptyCustomVisualizationTemplate'

      - name: Check WebpackD3VisualizationTemplate (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Templates/WebpackD3VisualizationTemplate'

      - name: Check WebpackReactVisualizationTemplate (full)
        uses: ./.github/workflows/actions/check-package
        with:
          working-directory: './Templates/WebpackReactVisualizationTemplate'
